<link rel="stylesheet" href="/bower_components/animate.css/animate.css" type="text/css" />
<link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.css" type="text/css" />
<link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.css" type="text/css" />
<link rel="stylesheet" href="/styles/font.css" type="text/css" />
<link rel="stylesheet" href="/styles/app.css" type="text/css" />
<link rel="stylesheet" href="/styles/themify-icons.css" type="text/css" />

<div class="row">
  <div class="col-lg-6 col-lg-offset-2">
    <div class=""><img src="/images/bigLogo.png" alt="GranPlay" height="65" width="212"></div>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="panel-body">
      <h1>Summary - Privacy Policy</h1>
      <ol style="">
        <li style=""><a style="color:#FDBA4F">Notice</a></li>
        <li style=""><a style="color:#FDBA4F">GranPlay Contact</a></li>
        <li style=""><a style="color:#FDBA4F">Information That We May Collect, Use And Store When You Access Or Use Our Applications, Such As User Or Visitor</a>
          <ol type="A">
            <li style=""><a style="color:#FDBA4F">Register</a></li>
            <li style=""><a style="color:#FDBA4F">Profile</a></li>
            <li style=""><a style="color:#FDBA4F">Publications, Posts, Conversations Etc.</a></li>
            <li style=""><a style="color:#FDBA4F">Games / Matches / Championships / Competitions Etc. (Events)</a></li>
            <li style=""><a style="color:#FDBA4F">Agendas</a></li>
            <li style=""><a style="color:#FDBA4F">Results</a></li>
            <li style=""><a style="color:#FDBA4F">Surveys (What Others Can Do And You)</a></li>
          </ol>
        </li>
        <li style=""><a style="color:#FDBA4F">How We Use, Treat And Store Information</a></li>
        <li style=""><a style="color:#FDBA4F">Sharing Information With Third Parties</a></li>
        <li style=""><a style="color:#FDBA4F">Use Of Data In Case Of Change Of Control Of GranPlay</a></li>
        <li style=""><a style="color:#FDBA4F">Restrictions By Age And Geography And Others</a></li>
        <li style=""><a style="color:#FDBA4F">Safety</a></li>
        <li style=""><a style="color:#FDBA4F">Links To Other Sites</a></li>
        <li style=""><a style="color:#FDBA4F">Choose / Opt-Out</a></li>
      </ol>

      <h2>1. Notice</h2>
      <p>This privacy policy describes GranPlay's privacy practices, its applications and related services, sites owned or operated by GranPlay and its corporate affiliates (collectively, the "Service" or "Services")).</p>
      <p>The use of any of our services is subject to this Privacy Policy, the Terms and Conditions and other rules that accompany our applications, IN CONJUNCTION. BY USING ANY PART OF OUR SERVICES, YOU ARE ACCEPTING THE PRACTICES SET FORTH IN THIS PRIVACY POLICY, THE TERMS OF USE AND OTHER RULES IN OUR APPLICATIONS. If you do not accept any of them, at any time, you must cancel your subscription and discontinue use. The use of our services demonstrates that you agree to our rules, terms and policies.</p>
      <h2>2. GranPlay Contact</h2>
      <p>If you have any questions about this Privacy Policy, Terms of Use, our rules and practices of our services, you can contact us by email: contato@granplay.com</p>
      <h2>3. Information That We May Collect, Use And Store When You Access Or Use Our Applications, Such As User Or Visitor</h2>
      <p>We share the types of information we collect from you in two general categories: personally identifiable information (IPI) and non-personally identifiable information (non-IPI). IPI consists of any information that can be used to identify you specifically as an individual, while non-IPI consists of aggregate information or any information that does not reveal your identity. The following sections describe how your IPI and non-IPI are collected by us and how we use such information. When we inform information, without limiting IPI or non-IPI, the application can be for both.</p>
      <p><b class="bold-text">When you sign up for our services and applications, we collect a variety of information about you to complete your profile. Except as otherwise provided in this Privacy Policy, we only disclose your information to other users and third parties for the proper functioning of the applications and identification needs. If you choose to connect to GranPlay through other applications, such as FaceBook or any other, we will receive and retain basic account registration data that you provided and provides to that service, such as name, email address, user, friend list, URL profile page. In addition, we will collect your terminal numbers as a phone number.</b> By collecting data from your terminal, we will send messages and warnings via e-mail, WhattsApp or similar, SMS, terminal operating system, Chat or other means.</p>
      <p>When you subscribe to our services, we may require your telephone number, terminal, e-mail address or registration / registration number of the Association and others in which you are affiliated. We use them both for transactional purposes (for example, activity updates) and for identification purposes, and for promotional purposes (for example, newsletters, new product offerings, event notifications, third party promotions, etc.). Messages that we send to you may contain codes that allow our database to control the use of messages, including whether it was opened, forwarded, or clicked. We reserve the right to send you certain necessary communications, such as service announcements and administrative messages, without giving you the opportunity to choose not to receive them in some cases of important notices. If you are no longer interested in receiving promotional emails, you can opt-out, with no-receive option.</p>
      <p><b class="bold-text">Demographic data may also be collected by the services.</b> We use this data to tailor the experience of our visitors and users by showing them the content that we think they might be interested in, so we can display the content according to your preferences. <b class="bold-text">Some of this information may be shared with advertisers on a non-IPI basis.</b></p>
      <p>We may periodically conduct surveys with volunteer users. We encourage our users to participate in these surveys because they provide us with important information about improving the service.</p>
      <p><b class="bold-text">We may collect and send information to and from the participating entities of our applications (Associations and others) of which you are a part. We are not responsible for the information that is passed to us by these entities and published in our applications.</b> You should ask for possible correction or make complaints about this information before these entities (also known as third parties). <b class="bold-text">This information may be accessed by other users in our applications.</b></p>
      <p><b class="bold-text">Everything you post and all your interactions, including those you own, will be part of our platform and you, hereby, assign and authorize the use by us of such information, posts, images, audios, etc. free of charge and for life, in any capacity and in any country, including for the custody, hosting, maintenance, use, reproduction, adaptation, sale, license, exploration, publicity and any other, guaranteeing by itself and its successors said authorization and assignment, even after the end of your participation as a user of our platform. You agree to be the owner of everything you share, post or report.</b></p>
      <p><b class="bold-text">You agree not to infringe third party rights through our applications. For example, but not limited to, you may not offend the honor and privacy of persons, use of images, videos, audios, texts or any others that are not yours or that you are not authorized to use. You will be fully responsible for your actions in our applications.</b></p>
      <h4>A. The Register</h4>
      <p>You can change your data, such as email address, password and other information, from the access "Account Settings" or similar, accessible via a link from our applications. To the extent that you choose to include IPI or other information in your profile, the service allows you to update or remove this information when editing or deleting content, but<b class="bold-text"> many information already published in the applications there will remain and can not be removed by you.</b></p>
      <p>In order to confirm your affiliation with some Associations, you must inform us of a password and possibly other information, to be provided to you by the Association itself. The obtaining, correction, control, custody, care and sending to us of these data are of its total responsibility. The data to be sent by you must be true, current and accurate. You must keep your data and access keys up to date with GranPlay, otherwise services and access will be interrupted.</p>
      <h4>B. Profile</h4>
      <p>You may be asked to create a profile in your account as well. Profile data will also be used within our applications to identify you in a variety of ways in order to enable our services and make your experience richer.      <b class="bold-text"> Your profile may be used and shared by us, other users, and even third parties who are interacting with our applications.</b> What you include in one platform may appear in another. <b class="bold-text">Your profile, photos, comments, movies, audios and all information will be available in our applications and some, such as your comments and posts, or about you in chats, scores, results, etc., will be in applications and in certain situations to the public in even after the termination of your account. You can change certain data in your profile.</b></p>
      <p>After creating an account, you may include in the applications information not filled out during your registration, such as media files (photo, sound and video), matches and events before and after registration, comments, classifications, positioning, address, matches, among others. Providing additional information will allow you to gain more benefits from GranPlay, helping you to build championships, games, statistics, offers, and more. <b class="bold-text">By completing this data, you authorize us to post it for viewing and use by users, visitors and Associations.</b></p>
      <h4>C. Publications, Posts, Conversations Etc.</h4>
      <p><b class="bold-text">All comments, information and posts from you or from you in the public places of the applications will be available in both the application and the web page and other means and will be available to the users and visitors of our services. Once you've posted this information for yourself or you, in public places, or in other users' chats and locations, you can not delete them. Any information that is disclosed in these areas becomes public information and you should exercise caution when posting any IPI. WE RECOMMEND YOU NOT TO PUBLISH ANY IPI IN THE PUBLIC PLACES OF THE APPLICATIONS AND NOT EVEN IN CONVERSATIONS WITH OTHER USERS. We will do our best to erase all information with possible cancellation of your, however, some information can not be withdrawn.</b></p>
      <h4>D. Contacts and friends</h4>
      <p>We offer tools to help you load your friends' data and addresses from your terminal or other applications so you can find your friends on the services and invite your contacts who do not have GranPlay accounts to join. <b class="bold-text">If you authorize us or provide your password to retrieve these contacts, we will not save your password after you have uploaded your contact information, however, we will retain your contact information. We will send your designated contacts one or more e-mail messages or other means containing your name, our message template, our words and / or media, inviting you to participate in our services, which may include or reminder messages.</b> These emails also include instructions on how these friends or contacts can remove your information from our database.</p>
      <p>In this case, we will store this information (including phone numbers) and use it to help you manage and increase your contacts in connection with our Services. <b class="bold-text">We may also use this information to display to you and to other Users that you have in common, regardless of whether those contacts are Users or not. We can also suggest that a user join their network of friends / partners, be it by their location, score, likes by games, teams, classification etc., or by the common contacts.</b> This service is similar to what you already know in other social networking applications.</p>
      <h4>E. Games / Matches / Championships / Competitions Etc. (Events)</h4>
      <p><b class="bold-text">You can sign up for various events you participated in or participate in and post on them. This information will be used statistically and even individually (non-IPI and IPI).</b> The locations, punctuation, opponents, styles, photos, chats, time etc. of these events will be published in the applications and used to promote and / or organize events, championships etc. <b class="bold-text">You can enter and enter other users in the events and have your data used by third parties in these insertions and enter data of other users. Accordingly, you agree that this information will be made public to other users, entities, and public places of the applications, including to non-users. Likewise, you will make data from the friends you include in this public information.</b></p>
      <h4>F. Agendas</h4>
      <p><b class="bold-text">To synchronize and organize your events and between you, other users and Associations, we may use data from your calendar and share it with third parties.</b> Likewise, by accepting or being invited to attend events, the application will include them in your terminal's agenda and share them with other users. Depending on your schedule and location and cross-checking of other data, such as scoring, preferred sports, teams, preferences etc., you may be able to suggest events and likewise suggested events to third parties where you appear. <b class="bold-text">We will get agendas and availability data from the Associations of which you are a member.</b></p>
      <h4>G. Results</h4>
      <p><b class="bold-text">Some results from your events or events that you participate in may be shared in the applications and displayed to others.</b> In some cases, this data may become public. <b class="bold-text">Even after the cancellation of your subscription, some results may still be in the event history of applications, chats and others. You are aware that such results will be shared publicly, even to non-users.</b></p>
      <h4>Surveys (What Others Can Do And You)</h4>
      <p><b class="bold-text">Third parties may conduct surveys about you to invite you to attend events. Because they are online applications, your information may also appear in search engine results on the internet,</b> as well as social networking information that is currently widely used.</p>
      <h2>4. How We Use, Treat And Store Information</h2>
      <p><b class="bold-text">Log Files: Whenever you access our services or applications, our servers or servers that we use may automatically collect information from your browser, device, or terminal. This information may include IP addresses and type of browser (if you are using a browser), device or terminal ID, location (if you have enabled this function), Internet service provider, wireless service provider, referring pages output, platform type, date / time log, and number of clicks. </b>We can use this information to analyze trends, manage services, prevent fraud, track visitor movements, and gather demographic information. We do not share this information externally, unless we are required by law or in cases of some crimes with this prediction in the Brazilian Civil Registry and other legislation in which, if required by the Administration or State, such as the Police Administration, we may send this data . This information is considered to be non-IPI.</p>
      <p><b class="bold-text">Cookies: We may use cookies to keep track of certain types of information while you are visiting our applications and services. </b>Cookies are small files placed on your computer or terminal. They allow us to count the number of visitors in our applications and distinguish repeat visitors from new visitors. They also allow us to save user preferences and user usage trends. We have cookies for the proper functioning of our services, so if your browser or terminal is set to reject all cookies, the services may not work properly. <b class="bold-text">Users who refuse cookies or similar tools assume all responsibility for any loss resulting from functionality in the Services.</b></p>
      <p><b class="bold-text">Analytics Services: We may use our own or third-party Analytics services, such as Google, to help us analyze how users use the services. </b>The information generated by your browser or terminal about your use of the Service will be transmitted and stored by the Analytics Provider in Brazil, the United States, or other countries, depending on where these companies store the information. Analytics Providers will use this information for the purpose of evaluating your use of the Service, compiling reports about your activity for our use and providing other services relating to user activity. The Analytics Service Providers may also transfer this information to third parties, where required by law, or if such third parties process the information on behalf of the Analytics Suppliers or, depending on the legislation of each country. <b class="bold-text">By using our Services, you consent to the processing and transfer of data about you by Analytics Providers in the manner and for the purposes described above.</b></p>
      <p>Web Beacons: Web beacons (also known as cleargifs and pixel tags) are small transparent graphic images that are often used in conjunction with cookies to further customize our applications to users and to collect a limited set of information about our visitors. <b class="bold-text">We may also use web beacons in e-mail communications to understand the behavior of our customers, users, and potential users.</b></p>
      <p>All your information to us may be stored and maintained for a period of 06 (six) months or more.</p>
      <p>Through the above tools, we or third parties can send you advertising and advertisement. If you do not want to receive them from a certain entity, you can opt out in the messages.</p>
      <h2>5. Sharing Information With Third Parties</h2>
      <p><b class="bold-text">You acknowledge and agree that we may disclose information about you and third parties that you provide to us if: (a) we believe in good faith that we are authorized or required to do so by law; (b) you give us your consent to do so, including if we notify you that the personal information provided will be shared and you provide such information; (c) we believe that disclosure is reasonably necessary or appropriate for: (1) compliance with law, requests or orders for law enforcement, or any legal / judicial process (whether or not such disclosure is required by applicable law, depending on interpretation for us); (2) protect and defend the rights or property of GranPlay, its users or third parties; or (3) protect one's health or safety.</b></p>
      <p>Disclosure to participating entities (Associations and others) and other users: <b class="bold-text">All your information to us sent by you or third parties in our applications may be shared with the partner entities and with other users, as this is required for the proper functioning of the application. </b>Your passwords will not be shared, however, <b class="bold-text">even your card numbers may be shared with the partner entities if we happen to mediate any payment. We will treat this information as confidential, using tools for your safety.</b></p>
      <p>Disclosure to Third Parties: We may share your non-IPI with third parties, but not in a way that may disclose your identity. For example, when you access a page on our site, a cookie can be automatically set by us or by our service providers recognize your browser as you browse the Internet and present it with information and advertising based on your apparent interests.</p>
      <p><b class="bold-text">We may share your IPI, sometimes in conjunction with your non-IPI, with service providers who may be associated with us to perform functions on our behalf. </b>For example, outsourced customer support agents or technology infrastructure providers may need access to your information to perform services for you. Your information will be treated as private and confidential by these service providers and not used for other purposes that we do not authorize. <b class="bold-text">In addition, from time to time, we may share IPI over our user base with carefully selected third parties so that they can offer products and services that we believe may be of interest to our users. </b>If you do not wish to receive offers from our trusted partners, you can change your email preferences or messages at any time by following the steps outlined in the "Opt-Out" section in them.</p>
      <p>Third Party Advertising: We may use third-party advertising agencies or other service providers to serve ads on the Services on behalf of GranPLay or third-party advertisers (for example, retailers of goods or services). These third parties may use cookies and web or other beacons to measure the effectiveness of advertising. Any information that these third parties collect through cookies and web beacons is anonymous.</p>
      <h2>6. Use Of Data In Case Of Change Of Control Of GranPlay</h2>
      <p><b class="bold-text">As we develop the GranPlay business, we may buy or sell assets and, depending on the transaction, the IPI and non-IPI may be transferred assets. </b>If we are acquired, suffer a change in administrative control or in any way incorporated by third parties, even in bankruptcy, our IPI and non-IPI may be part of the assets transferred to the acquirer, administrator or successor. If this occurs, you will be notified if there is any relevant change in how IPI is collected or used.</p>
      <h2>7. Restrictions By Age And Geography And Others</h2>
      <p>Our age restrictions for use of our services and applications are set forth in our Terms of Use. <b class="bold-text">We do not target any part of our services or applications that are not civilly fully capable. We may at our discretion exclude your information and accounts if we believe that you are not fully capable and of legal age under the laws of Brazil and your country.</b></p>
      <p>Depending on your location and time, your access and use of our services may be adversely affected. <b class="bold-text">We use tools that can help us locate you.</b></p>
      <p><b class="bold-text">You will not be able to access, subscribe to or use our services if you are not authorized according to the laws of your country.</b></p>
      <h2>8. Security</h2>
      <p>We have adopted security measures to protect against the loss, misuse and alteration of the information stored in our database. We will exercise due care in providing the secure transmission of information between your terminal or device and the servers we use, however, <b class="bold-text">no information transmitted over the Internet can be guaranteed as 100% secure, so we can not ensure or guarantee the security of any information that has been transmitted to us through the Internet and, therefore, we are not responsible for any accidental interception or misuse.</b></p>
      <h2>9. Links To Other Sites</h2>
      <p>We are not responsible for the privacy practices or the content of other sites that may be connected to our services or any third parties.</p>
      <h2>10. Choose / Opt-Out</h2>
      <p>You can use the following options to remove your information from our list of email addresses and messages if you choose not to receive promotional emails and newsletters</p>
      <p>Click the "unsubscribe", "no more receive" or a similar link at the bottom of the email or message received;</p>

    </div>
  </div>

</div>

<style>
.pink {
  color:#DB7093	;
}

.bold-text {
  color:black;
}
</style>
