<link rel="stylesheet" href="{{ route('baseurl') }}/bower_components/animate.css/animate.css" type="text/css" />
<link rel="stylesheet" href="{{ route('baseurl') }}/bower_components/bootstrap/dist/css/bootstrap.css" type="text/css" />
<link rel="stylesheet" href="{{ route('baseurl') }}/bower_components/font-awesome/css/font-awesome.css" type="text/css" />
<link rel="stylesheet" href="{{ route('baseurl') }}/styles/font.css" type="text/css" />
<link rel="stylesheet" href="{{ route('baseurl') }}/styles/app.css" type="text/css" />
<link rel="stylesheet" href="{{ route('baseurl') }}/styles/themify-icons.css" type="text/css" />

<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class=""><img src="{{ route('baseurl') }}/images/bigLogo.png" alt="GranPlay" height="65" width="212"></div>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="panel-body">
      <h1>Summary - Terms of Use</h1>
      <ol style="">
        <li style=""><a style="color:#FDBA4F">Warnings And Introduction</a></li>
        <li style=""><a style="color:#FDBA4F">Changes To These Terms</a></li>
        <li style=""><a style="color:#FDBA4F">Nomenclature And Basic Settings:</a></li>
        <li style=""><a style="color:#FDBA4F">Objectives And Information About The Application</a></li>
        <li style=""><a style="color:#FDBA4F">Beginning Of Use And Registration:</a></li>
        <li style=""><a style="color:#FDBA4F">Data Upload And Calendar Synchronization</a></li>
        <li style=""><a style="color:#FDBA4F">Propaganda Conducted In Associations And Associations In Our Applications</a></li>
        <li style=""><a style="color:#FDBA4F">Use Of Our Services:</a></li>
        <li style=""><a style="color:#FDBA4F">Structure Exposed And Available In Applications By Associations</a></li>
        <li style=""><a style="color:#FDBA4F">Method Of Payment Association / GranPlay.</a></li>
        <li style=""><a style="color:#FDBA4F">Interaction With Other Applications Or Entities</a></li>
        <li style=""><a style="color:#FDBA4F">Intellectual Property</a></li>
        <li style=""><a style="color:#FDBA4F">Contractual Relationship</a></li>
        <li style=""><a style="color:#FDBA4F">Disputes Between Associations, Users, Members Or Third Parties:</a></li>
        <li style=""><a style="color:#FDBA4F">Other Provisions Regarding Waiver Of Liability:</a></li>
        <li style=""><a style="color:#FDBA4F">Final Dispositions:</a></li>
      </ol>

      <h2>1. Notices And Introduction</h2>
      <p>GranPlay is an application, service and trademark of Wilson Saburo Honda Property and all its rights are reserved to it, including those of Intellectual Property of all its trademarks, patents, copyrights, layouts, systems, software, drawings, characters , texts and others.</p>
      <p>These Terms of Use integrate our Contracts and Policies with users, visitors, customers, partners, entities and others. <b class="bold-text">You must read carefully and agree to our terms so that you can be our partner, thus avoiding harm to yourself and others.</b></p>
      <p><b class="bold-text">These Terms and our Policies are contracts of adhesion</b> and your entire relationship with GranPlay and partner companies are based on good faith and good manners. <b class="bold-text">By using our applications in partnership, you declare to be civilly capable under the laws of Brazil (or your country), and have powers to represent your Association. By agreeing to this, you will be agreeing on behalf of the Association, even if it is referred to as "you", "Association", "Partner", "partner", "third party" or other designation to you in these Terms.</b></p>
      <p><b class="bold-text">In the event that you do not agree to our Terms and Policies, you may not and will not be permitted to be our partner or use our applications, platforms or services, regardless of the medium in which they are located. Use will demonstrate that you are capable and that your Association agrees.</b></p>
      <p><b class="bold-text">Your associates will be treated as users of our applications. They must accept our Terms and Policies.</b></p>
      <p>It is important that you know that we will collect <b class="bold-text">data from the Association (your company or you, if it is direct partners), your and your associates, as well as connection and access records, photos, location, time, punctuation, messages exchanged with users and various others, which may be freely used by us and which are assigned by your Association from now on, without temporal limitation or use.</b> We will do our utmost to respect the identity of the Association, its members, users, as well as identity and privacy, however, the gathering of information may deliver location to third parties, display photos, conversations and other users or former users.</p>
      <p><b class="bold-text">We interact, treat, collect and deliver data to other applications such</b> as Facebook, as well as information from the user's and Association's handset or terminal (cellphone, tablet, computer, or other device you are using to connect to GranPlay). We are not responsible for the use that these other applications will make with the data, however, when using our services, the Association agrees with these interactions and exchanges.</p>
      <p>When the Association installs or uses any third party application for use of GranPlay or from GranPlay, it is accepting the terms of use of the other applications, applications or platforms, as well as its updates, as the case may be, in addition to being responsible for the veracity information that the Association or its terminal transmits. This also applies to Plugins or other connections and interactions.</p>
      <p><b class="bold-text">We do not have or have editorial control over the content of what people or applications post or do on our platforms or applications, so we are not responsible for them.</b> If your Association feels impaired by any post or communication, you may report them to us and, in the form of the Law, we may withdraw the publications, if we understand it as correct.</p>
      <p>However, the Association <b class="bold-text">is prohibited from performing, indicating, mediating, fomenting or allowing posting of images, phrases, videos, sounds, audios, music or other uses that are offensive or disrespect Brazilian Law, morals and good customs and its Local law.</b> If we identify use or posting contrary to the law, we may remove them from our platforms without prior notice and without the right to appeal, at any time, in addition to taking appropriate legal measures.<b class="bold-text">Examples of illegal and non-permitted uses include: Offenses, pornography, terrorism, racial crimes, publications that indicate any type of prejudice, such as race, color, sex, gender, sexual orientation, religion, etc. of builling, crimes against intellectual property, placement or help placing third parties at risk, copy, counterfeit etc.</b></p>
      <p><b class="bold-text">The Association may not use user data as the basis for advertising, marketing or any other use except the data required for your participation in GranPlay.</b></p>
      <h2>2. Changes To These Terms</h2>
      <p><b class="bold-text">These terms may be modified at any time.</b> In the event of a change, we will send you a notice at the email address or telephone number you provided to us, which appears on your registration, and it will be up to you to read and agree or not with the changes. <b class="bold-text">The changes will take effect at the time of your publications. If you do not agree, discontinue using the services as a partner, be it applications, platforms or others, including canceling your account. Continued use will be construed as acceptance of the change in Terms and Policies. It is mandatory that you read the Terms and Policies frequently to be aware of any changes. If you do not agree to the changes, you will not be able to continue to use the Services nor be our Partner.</b></p>
      <h2>3. Nomenclature And Basic Definitions:</h2>
      <p>Some important definitions in this Term and in other GranPlay documents and Policies are:</p>
      <p>- Association (s): Clubs, courts, condominiums, spaces, entities, parks, gardens and others: Places where the user can book, rent or use space for sports and interaction with other users, to use and become partners with GranPlay.</p>
      <p>- User: Any person who uses or visits any of our platforms, even as a visitor, paying or not for our services, member, partner or third party. You may be referred to as "User" or "you".</p>
      <p>- Platform (s), Service (s) or Application (s): These are the set of functionalities in GranPlay systems, applications, services, websites, software, digital indoor media and others that you access through Terminal. In some cases they may be used synonymously.</p>
      <p>- Terminal: Phone, smartphone, tablet, computer, notebook, digital indoor media or any device that connects to our applications.</p>
      <p>- Connection log: Set of information regarding the start and end date and time of an Internet connection or our platform, its duration and the IP address or location used by the terminal for sending and receiving data packets; - Terminal: Phone, smartphone, tablet, computer, notebook, digital indoor media or any device that connects to our applications.</p>
      <p>- Application access records: the set of information regarding the date and time of use of a given application from a given IP or terminal address.</p>
      <h2>4. Objectives And Information About The Application</h2>
      <p>The application works on different platforms such as web sites, indoor digital media and mobile applications that will help your Association promote, with the participation of other users and other Associations, a unique experience of interaction in the practice of sports such as tennis, golf, volleyball , soccer, handball, table tennis, foosball, snooker and others, subject to availability to you and in your region.</p>
      <p>Through GranPlay, users and Associations can schedule matches, organize championships, rent blocks and fields, know who is playing where, help build categories, talk to users and Associations, use our chat, and share photos and videos, remembering that some these functions will be available in the future, in addition to possible others, but not all will be made available at all times and in their location.</p>
      <p class="pink">Through GranPlay, users and Associations can schedule matches, organize championships, rent blocks and fields, know who is playing where, help build categories, talk to users and Associations, use our chat, and share photos and videos, remembering that some these functions will be available in the future, in addition to possible others, but not all will be made available at all times and in their location.</p>
      <p class="pink">You, as an Association, may make available to GranPlay users their structure, such as courts, fields, halls, and others, where you can practice sports and physical activities in general, providing values, schedules, rules and other information. The user will interact by the application and can mark their activities, reserving spaces and making the payment directly or through the applications.</p>
      <p class="pink">Users will be able to sort their facilities and services, organize championships and others before you, adapting to their rules in the applications. For example, the Association should advise if only its Members may use its facilities or if any other GranPlay user may do so. User data can be sent to you via application, to a usage control register.</p>
      <p class="pink">The Association shall keep updated and send to GranPlay any changes to the list and data of its members. GranPlay, in turn, will send Associations information about users interested in using their facilities, times and preferences. It is up to the Association to accept and organize or not such imputs and to send back, through synchronization of agenda in the application, the data of the rented premises and their schedules. GranPlay's own application will help you in organizing and controlling your activities.</p>
      <p class="pink">The schedules and possibilities of the activities will be confirmed between Users and Associations through the applications. Associations should send accurate, true, and up-to-date data to applications and users so that there is neither lack nor duplicity. As soon as any time or rule changes in the Association, you must immediately update this data in GranPlay. If any reservation is made with previous rule, it will be valid.</p>
      <p><b class="bold-text">GranPlay has no responsibility for its actions or actions of the Associates, third parties, in addition, Associations and users are responsible for providing and maintaining the connectivity of their own terminals to access our services.</b></p>
      <p class="pink">GranPlay does not figure as part of the transactions between users and Associations, does not offer structure and does not exert any interference in the transactions carried out through the applications. The GranPlay only licenses the right of use of the Platform to the parties, by means of which these transactions can be carried out. GranPlay can not be considered, in any case, an intermediary of the negotiation between Users and Associations. Because GranPlay does not appear as a party to the rental and other transactions through the Platform, GranPlay can not oblige the parties to honor their respective obligations, and may only alter, limit and terminate access and availability by the applications.</p>
      <h2>5. Start Of Use And Registration:</h2>
      <p class="pink">The Associations will have specific place to register in our applications. This site will only be available on our website, <span style="color:black">www.granplay.com.</span> In the inscriptions, data of the Associations, such as full name, CNPJ, address, contact data, structure data, prices, schedules etc., besides user and password will be requested.</p>
      <p>Only after sending information and accepted, you can become a Partner Association. <b class="bold-text">GranPlay may require bank details of the Association so that it has access to the features.</b></p>
      <p><b class="bold-text">The Association shall complete the entries with accurate, unique, accurate and true information, which shall be kept up-to-date by it.</b> If you know of any misrepresentation or misrepresentation or misrepresentation of yourself or your associates, you should notify us immediately. The Association is responsible for all information you send us, both in civil and criminal matters.</p>
      <p><b class="bold-text">We may collect data from Members and users of other platforms, such as Facebook, WhatsApp, Google, Android, Apple, iOS, Windows, among others, to make an application easier and faster.</b></p>
      <p>When creating the password of the Association, we recommend that you use a strong password and keep it in a safe place or decorate it, not informing third parties, as we are not responsible for access or use of third parties made with your username and password, and we will interpret everything use with your user as performed by your Association.</p>
      <p><b class="bold-text">You are entirely responsible for maintaining the confidentiality of your Association password or password. You agree not to use the account, username, email address or password of another person or Association at any time or disclose your password to any third party.</b> You agree to inform us and change your password immediately if you suspect any unauthorized use of your account or access to your password. You are solely responsible for all and any use of your account or the Association account. GranPlay may request identity or password confirmations by other means, such as phrases, phone messages, e-mails, and more.</p>
      <p>To register, it may be necessary, among other data, to inform a cell phone number that represents the Association. GranPlay can make use of the notifications in its own Terminal, for example, interactive warnings on your cell phone.</p>
      <p><b class="bold-text">Data of your terminal and the Association, such as location, calendar, name, numbers, users, camera, audio, screen and others may be collected, used and made public by us.</b> We can suggest interactions between the Association, third parties and people, either by location, by rating of scores, likes, marketing data or others.</p>
      <p>By signing up, you and the Association commit to participating in our applications with the one and only sense of promoting sports, friendship, civility, healthy interaction with other people and places, respecting others and helping others. GranPlay to encourage these acts, denouncing who you believe to be acting contrary to these objectives.</p>
      <p>GranPlay will depend on confirmation from the Association administration for the user to interact with and practice activities with them and other users. GranPlay is not responsible for the registration of the user or the Association before third parties nor does it guarantee the sending by them of any information. If there is any conflict in this regard, it should be resolved directly with these third parties or users. The Association shall verify the truthfulness and be responsible for the information of its associates that it provides us.</p>
      <p>GranPlay will depend on confirmation from the Association administration for the user to interact with and practice activities with them and other users. GranPlay is not responsible for the registration of the user or the Association before third parties nor does it guarantee the sending by them of any information. If there is any conflict in this regard, it should be resolved directly with these third parties or users. The Association shall verify the truthfulness and be responsible for the information of its associates that it provides us.</p>
      <p><b class="bold-text">When registering and using our services, you declare, in addition to what is present in this Term, under the penalties of the Law: - If Legal Representative of the Association; - Be over 18 years of age, fully capable, civilly and mentally; - Just provide true information. - Perform and maintain only one (1) register with us updated and complete. If you forget your access data, you can retrieve them through our systems, which will allow you to register new password and recover data. - Keep precise and updated data in your register and in the register of Associates that you send us. - Do not commit illegal acts and respect the law and rights of third parties and ours, including those of intellectual property rights; - Respect our Terms, Policies and Rules, as well as the other Associations and other entities with which it will interact through our application or in which it will participate in any activity, aware that rules and standards must be verified before these entities and may, if they are made available, be also available on GranPlay. - You must make available in the GranPlay all the rules of the Association, clearly and completely. - You must send to GranPlay all the schedules, costs, features and availability of your structure, as well as the relative costs to use. - You may grant access to the Platform (s), Service (s) or Application (s) to other administrators, with mastery or restricted access to certain functionalities. Be cautious in granting this assignment, as you will also be responsible for the settings, information and updates. GranPlay reserves the right to cancel any registration that it deems to be duplicitous or contrary to its Terms and Conditions, without any previous notice, explanation, nor return of information, images and values. We are not liable for any untrue information from you or third parties, but we may take the contrary legal measures aiming at termination, penalty and indemnification.</b></p>
      <p><b class="bold-text">When registering and using our services, you declare, in addition to what is present in this Term, under the penalties of the Law: - If Legal Representative of the Association; - Be over 18 years of age, fully capable, civilly and mentally; - Just provide true information. - Perform and maintain only one (1) register with us updated and complete. If you forget your access data, you can retrieve them through our systems, which will allow you to register new password and recover data. - Keep precise and updated data in your register and in the register of Associates that you send us. - Do not commit illegal acts and respect the law and rights of third parties and ours, including those of intellectual property rights; - Respect our Terms, Policies and Rules, as well as the other Associations and other entities with which it will interact through our application or in which it will participate in any activity, aware that rules and standards must be verified before these entities and may, if they are made available, be also available on GranPlay. - You must make available in the GranPlay all the rules of the Association, clearly and completely. - You must send to GranPlay all the schedules, costs, features and availability of your structure, as well as the relative costs to use. - You may grant access to the Platform (s), Service (s) or Application (s) to other administrators, with mastery or restricted access to certain functionalities. Be cautious in granting this assignment, as you will also be responsible for the settings, information and updates. GranPlay reserves the right to cancel any registration that it deems to be duplicitous or contrary to its Terms and Conditions, without any previous notice, explanation, nor return of information, images and values. We are not liable for any untrue information from you or third parties, but we may take the contrary legal measures aiming at termination, penalty and indemnification.</b></p>
      <p><b class="bold-text">When registering and using our services, you declare, in addition to what is present in this Term, under the penalties of the Law: - If Legal Representative of the Association; - Be over 18 years of age, fully capable, civilly and mentally; - Just provide true information. - Perform and maintain only one (1) register with us updated and complete. If you forget your access data, you can retrieve them through our systems, which will allow you to register new password and recover data. - Keep precise and updated data in your register and in the register of Associates that you send us. - Do not commit illegal acts and respect the law and rights of third parties and ours, including those of intellectual property rights; - Respect our Terms, Policies and Rules, as well as the other Associations and other entities with which it will interact through our application or in which it will participate in any activity, aware that rules and standards must be verified before these entities and may, if they are made available, be also available on GranPlay. - You must make available in the GranPlay all the rules of the Association, clearly and completely. - You must send to GranPlay all the schedules, costs, features and availability of your structure, as well as the relative costs to use. - You may grant access to the Platform (s), Service (s) or Application (s) to other administrators, with mastery or restricted access to certain functionalities. Be cautious in granting this assignment, as you will also be responsible for the settings, information and updates. GranPlay reserves the right to cancel any registration that it deems to be duplicitous or contrary to its Terms and Conditions, without any previous notice, explanation, nor return of information, images and values. We are not liable for any untrue information from you or third parties, but we may take the contrary legal measures aiming at termination, penalty and indemnification.</b></p>
      <p><b class="bold-text">Failure to use the Application does not indicate your non-acceptance of the Terms or its version that is in effect if you are already a Partner Association,</b> so if you wish to stop using our services, you must cancel your account. In any case, we may, but are not obligated, at any time, to cancel and cancel your account, either for lack of use or for another reason.</p>
      <p>You will solemnly be responsible for the use and information that you carry out with your data on our platforms, so notify us promptly of any unauthorized use of your account with us, violation or loss of password.</p>
      <p>You must report to GranPlay any and all irregularities or problems related to the operation of the Applications or other irregularities related to users.</p>
      <h2>6. Data Sending And Calendar Synchronization</h2>
      <p>GranPlay provides a set of tools and dashboards in the Platform for the Association to administer its users and the structure available, whether it is considered as court, field, hall, table, equipment, balls, rackets etc.</p>
      <p>The Association will be responsible for the entry, updating and synchronization of the information and data in the Platform, such as: administrators, users, calendar of the blocks, configuration of the rules of the Association, etc.</p>
      <h2>7. Propaganda Carried Out In Associations And Associations In Our Applications</h2>
      <p>GranPlay may make available in the Associations monitors at specific locations and to be accepted by the Association in which GranPlay will administer the Digital Indoor Media, in which the agenda and availability of the Association structure, contents, news and advertisements chosen by GranPlay will be made available. If the Association has any restriction on any advertising, it must be informed to GranPlay that it will not be published.</p>
      <p>GranPlay will use information and news RSS feed, whether Rich Site Summary, RDF Site Summary or Really Simple Syndication, in high-profile and prestigious channels. In case the content disclosed is inappropriate, the Association must notify GranPlay, in the email contato@granplay.com, for the removal of this news. The Association exempts and declares that GranPlay is not responsible for such information.</p>
      <p>If the advertisements that are advertised by GranPlay are inappropriate for the Association, the Association must notify GranPlay, at contato@granplay.com, for their removal.</p>
      <p>The Association will not hold GranPlay responsible in any case for any damage caused by content conflicting with its interests, since GranPlay can not predict or control such situation.</p>
      <p>GranPlay will check the technical feasibility of removing such content and will take action as long as possible. As it is a complex and interactive system between several points, with information received by third parties, often unalterable, it can be delayed or even impracticable to withdraw some content, leaving the thistle of the Association to maintain or not the monitors triggered.</p>
      <p>The Association shall provide the security and integrity of the GranPlay devices and provide signal, power and internet access for the maintenance of the devices.</p>
      <p>The devices belong to GranPlay and are under its responsibility to maintain them, but the Association will be responsible for any damage due to improper use or improper disposal. The monitors will be in the Association in model of Deposit, answering the Association according to the Law.</p>
      <p>GranPlay reserves the right at any time to withdraw its monitors from the Association, as well as to stop issuing content at any time, without prior notice.</p>
      <p>Upon termination of the Association's relationship with GranPlay, any equipment within the Association's structures must be returned in perfect order to GranPlay within a maximum of five (5) business days after termination of the relationship, under penalty of fine of R $ 200.00 (two hundred reais) per day of delay in the return, corrected since the acceptance of the present by the IGPM.</p>
      <p><b class="bold-text">The use of our services must respect the Law of your country and Brazil - in all that is not contrary to Brazilian Laws - </b>the present Term of Use, our Privacy Policy and others that appear in our applications and refer to them by we.</p>
      <h2>8. Use Of Our Services:</h2>
      <p>Following your agreement and registration in our applications, the Association may communicate with other individuals and legal entities, post comments, photos, videos and other media, arrange and organize games, tournaments, championships and / or spaces for practicing sports activities, sharing results and others, and others may do so on the Association, depending on the feasibility of the application.</p>
      <p>GranPlay reserves the right to change and withdraw at any time partial accesses, totals or service packages of its applications broadly or individually from its users or Associations at any time and without prior notice, as well as to include our accesses, partial or total, to new packages and even platforms in their applications, in addition to making changes in the applications at any time, either for improvement or update, or by internal decision. The same applies to partners, Associations and others, which may be changed at any time, without prior notice. Users and associates of the associations may have their access denied or diminished at any time, without prior notice or justification.</p>
      <p><b class="bold-text">GranPlay may exclude or refuse to post or cancel any publication, game, organization, league, score, activity, access, connection or sharing or its or any third party with respect to the Association or users, without prior notice or explanation, by their own criteria.</b> For example, if the reservation of a space is not confirmed within the time provided in the application, it will be automatically canceled or made available to others. Such denial or cancellation may also be performed by Users, through GranPlay or directly to the Association. We have no control or responsibility for the acts performed by third parties.</p>
      <p><b class="bold-text">Under the terms of the Law, you agree that you may only use our services and post content and information in a way that does not infringe third party rights ,</b> which includes your user data relating to the Association, such as name, phone number, login, nickname and password. <b class="bold-text">The content you post must be owned by the Association or you must have the license and authorization to post them,</b> which includes the use of photos, videos, texts, images, audios, trademarks, copyrights and others. <b class="bold-text">You may not post confidential third party information or even any kind of data that even the public may injure third party right,</b> including GranPlay. No posting of content, image, video, text, audio or other related to racism, nudity, sex, pornography, child pornography, pedophilia, revenge, offense or any other harm to third parties or GranPlay is permitted. moral or material or that is contrary to: Law, order, good morals and good customs.</p>
      <p><b class="bold-text">However, how you will interact as an Association with third parties and may receive information or be exposed to content that is harmful to the Association, such as wrong scores, misrepresentation, aggression, deception, etc.</b></p>
      <p>The Association should always be very careful and zealous to post information from you and third parties, not expose themselves or expose themselves to third parties in an unnecessary way. Your data will be publicly posted. You are prohibited from posting or misusing personal information of any third party, whether associated or not.</p>
      <p><b class="bold-text">You agree not to use our platform for advertising, commercial or commercial purposes unless expressly permitted by us to you, and you may not use the platform to send Spams, disseminate viruses, collect data through any means such as phishing, web bugs, cookies, spyware and other similar practices such as data hacking, or making use of other software or tools such as collectors, robots, spiders or scrapers.</b></p>
      <p>The use and access to our platform is private and non-transferable and should be performed by an authorized person without the use of other software or tools. You are not allowed to access the platform using tools that make or attempt to make your IP anonymous. Anonymity is not allowed under Brazilian law.</p>
      <p>You may not rent or sell, in whole or in part, any data, punctuation, service or use of our applications, unless expressly authorized by us. You may not use the applications and data therein (including users) for purposes not expressly provided in these Terms.</p>
      <p><b class="bold-text">If you become aware of any breach of the Law or these Terms in our applications, you should notify us immediately after the notice.</b></p>
      <p><b class="bold-text">Everything you post and all your interactions, including those of which the Association is the holder, will be part of our platform and you hereby assign and authorize us to use said information on behalf of the Association, such as posts, images etc., for free and for life, in any title and in any country, including for the custody, hosting, maintenance, use, reproduction, adaptation, sale, license, exploration, publicity and any other, ensuring by itself and its successors said authorization and assignment, even after the end of its participation as a partner of our platform. You represent to be the owner or authorized by the owner of everything you share, post or inform.</b></p>
      <p>You must be aware and agree that GranPlay uses the data, images, punctuation and others of the Association - provided by you, other users or third parties - in media installed in your and other Associations. The content will be provided by GranPlay, which will include reservations schedule, sports news, advertisements and others. As content, photos, profiles and results of games and interactions of users, including the Association and its members, may be present.</p>
      <p><b class="bold-text">You also authorize us to obtain and maintain your access information to our platform, such as IDs, IP address, geographic data, access time, access and connection records, preferences and others, and authorize us to use all this information to improvement of our services, application of our services and use of this information for commercial and marketing purposes, including the sale, advertising and sharing of this information with third parties.</b></p>
      <p><b class="bold-text">You authorize us to send you information that we understand to be useful and advertisements that we understand to apply to you,</b> including the offering of our and third party products and services, including, <b class="bold-text">authorize third parties to send you advertisement directly and through our platform or even outside through your data we shared or the monitors available at your premises.</b> Communications can be done through various means, such as e-mail, signal to monitors, other applications or platforms, cellular, SMS, Chat and others.</p>
      <p><b class="bold-text">We are not responsible for any interaction you have with third parties, even if you access these third parties by having our platform or application as a starting point. It is important for you to know that our applications only make the connection between you, the user and third parties, whether they are associates or other Associations.</b></p>
      <p>You may cancel and terminate your participation / account with us at any time. <b class="bold-text">Upon termination of your membership in our platforms, for whatever purpose, no post, photo, text, video, audio, or other type of postings will be returned to you. It is up to you to perform any backup that you intend. Upon termination, we and the third parties who have obtained your data may continue to send you information, updates, offers, advertisements, and you are responsible for making the Outgoing Opt-Out option for each of these senders, including us. We may, in the same way, delete any and all content immediately after you leave or even during your participation, without notice. Comments, images, films and publications of yours or the Association may be retained even after you leave the public places of the Applications.</b></p>
      <p><b class="bold-text">You authorize users to record images, videos, audios, and others on your site and in which they appear. GranPlay has no responsibility for the abstraction or use of this information. If you do not want to authorize obtaining these data within your premises you must insert these watermarks into your space in GranPlay and take all the care internally so that this does not happen. The protection of your rights and assets is your responsibility and indemnity to any damages shall be requested directly from users, other Associations or third parties that cause them.</b></p>
      <p>GranPlay may take measures to comply with the provisions set forth herein, such as warnings, suspensions, cancellations, registrations, games, schedules, registrations and others.</p>
      <p>You agree to immediately inform GranPlay of any abuse or legal violation that you notice relating to any of the Services and / or users or other Associations, irrespective of their co-responsibility or obligation, without prejudice to taking reasonable steps to terminate such acts immediately .</p>
      <p><b class="bold-text">GranPlay and third parties, either directly or through GranPlay, may terminate games or other events or access at any time without notice. Pre-reservations, reservations, confirmations or cancellations are valid and operate according to the rules established by each Association.</b></p>
      <h2>9. Structure Exposed And Available In Applications By Associations</h2>
      <p>Every structure, whether it is considered as a court, field, hall, table, equipment, balls, rackets etc., that you make available through GranPlay must be in perfect conditions of use and comply with all the current legal norms, be the Federal, State, Municipal or other, such as security, cleaning, insurance, housing, fire, sanitary, etc.</p>
      <p>The Association is solely responsible for the structures it makes available to the public and will indemnify GranPlay for any and all costs and expenses, including those incurred by lawyers and lawyers, if they suffer damages or need for indemnification due to damages caused to users or third parties in view of the availability, use or lease of their structures. GranPlay does not undertake any analysis of the structures, however, it may limit, interrupt or cease any access of the Association if it becomes aware of or distrusts any wrong or misleading information, even through its users, regardless of being able to take the appropriate legal measures.</p>
      <p>The Association shall provide the relevant information on the characteristics of its structure available for use, responding to users or any third party due to any error or omission in completing the registration in the application.</p>
      <p><b class="bold-text">By registering information about its structure in GranPlay, the Association grants to GranPlay, its partners and users a free, perpetual and irrevocable license to use any and all content, photo or image posted in the applications, in any channels of disclosure, monitored on all Associations or on any other digital media.</b></p>
      <p><b class="bold-text">During the use of your structure, you must give all necessary assistance to users, whether in the provision of equipment and materials, or other normal needs to that sport, as if their associates or customers users, under treatment at least equal.</b></p>
      <h2>10. Payment Method Association / GranPlay.  </h2>
      <p>By the license of use of the applications, the Association will pay the 15% (fifteen percent) value of all the transactions that receive for the use of its structures.</p>
      <p>The use of the facilities may be paid directly by users or their Associates or may be paid through GranPlay, which will retain 15% (fifteen percent) of the amount of payments made by Associates or users through the applications.</p>
      <p>Once any Association credits have been established, they will be deposited in up to 5 business days in the current account informed by the Association in the Platform. It is important for the Association to keep the bank details up to date.</p>
      <p>When payments are made directly to the Association and the bookings have been made by the applications, the Association will have a debit created in the applications. These debts will be deducted from the next transfers of amounts or through the direct payment by the Association to GranPlay.</p>
      <p>Direct payment to GranPlay will be made as follows:</p>
      <p>If GranPlay provides any service or use of a free structure to GranPlay and / or users, such as a loyalty program, GranPlay may decide whether or not to charge you for using the application.</p>
      <p><b class="bold-text">GranPlay may</b> offer free or costly services to Users and Associations and may <b class="bold-text">at any time make any service free of charge and vice versa, without prior notice, it being up to you to decide whether to continue as an Associate or not.</b> The charges will be made by means of credit card debt. The values ​​and forms will be informed to you in the moments of acceptance, however, it is <b class="bold-text">up to you to follow our table of values ​​or third parties, partners or not, before accepting any payment.</b></p>
      <p><b class="bold-text">Payments to the Association by GranPlay will only be made after confirmation and reconciliation of the payment by users of the use of the assigned structure. In the case of payment by the user and not use of the facilities, even if previously scheduled, amounts may not be passed on to the Association, unless the cancellation is not given within the term and rules stipulated by the Association, at which time the amounts will be passed with the retention due to GranPlay.</b></p>
      <p>GranPlay licenses your application and communicates between you and third parties and you may, depending on what applications are made available, receive payments directly from these third parties or us, whether for services performed or other products that you offer. An eventual return policy for reservations will work as established by the rules of each Association - if possible inclusion in the format and rules of the applications - and / or our rules. <b class="bold-text">We are not responsible for any interaction you have with third parties, commercial or otherwise, even if this interaction has had as a starting point our applications or platforms.</b> What we do is put you and the users in touch by licensing our applications.</p>
      <p>The Association shall issue, whenever applicable, the Tax Notes to Users who rent their structures or purchase other products or services. Preferably, I receive a brief description of the use and the structure and the Nota Fiscal should be sent in the user's email.</p>
      <h2>11. Interaction With Other Applications Or Entities</h2>
      <p>GranPlay may direct you to, indicate or include third-party sites, profiles, and services, whether through Links or otherwise. Other Associations and users may do the same. <b class="bold-text">You will be entirely responsible for reading and accepting or not accepting the terms and conditions and policies with third parties and accessing or not to these third party websites or applications. If you accept the accesses, you are also accepting the terms and conditions and policies of third parties .</b> These Terms and Conditions apply to relationships with GranPlay and we can not guarantee or be responsible with your relationships with third parties, condition, already accepted and ratified by you. <b class="bold-text">We do not endorse or confer on third party content, profile, and applications.</b></p>
      <p><b class="bold-text">GranPlay assumes no responsibility for third-party ads or users that are posted on, through or in connection with the Services or Applications, nor assume any responsibility for the goods or services provided by these third parties, serving our platform merely as a possible communication guide between you and others.</b></p>
      <p><b class="bold-text">GranPlay makes its connection with third parties, being a means of connection, either between users and / or between user and third parties, such as Associations and others. We have no control or responsibility over your relationship with other Associations, users or third parties, nor information, requirements or rules exchanged.</b></p>
      <h2>12. Intellectual Property</h2>
      <p>GranPlay respects the rights of third parties and theirs, including those of intellectual property, and requires its users and Associations to do the same. <b class="bold-text">It is GranPlay's policy to terminate, in appropriate circumstances, the association, use, access or registration of infringers at its discretion and understanding, as well as to exclude content that we believe to be infringing products.</b></p>
      <p>GranPlay, your name, logo, services, application, platform, systems and other are owned by GranPlay and you are not authorized to use, copy or reproduce our unauthorized rights. <b class="bold-text">You agree not to copy, publish or otherwise use any data or rights of us or third parties, including source codes, lay outs, trademarks, patents, copyrights, designs, copyrights and other intellectual property rights, whether ordered or records.</b></p>
      <p><b class="bold-text">GranPlay's applications are and will be constantly built and modified with the use and support of its users and partner Associations, so we may make changes, withdrawals or additions from ideas, uses, images, videos and any publications or information from our users and partner associations. In this way, you authorize and assign us any rights, free of charge and without limitation of time or use, relating to them, without our having to inform you about uses or give you any accounts or clarifications, in any way, forcing you and his heirs and successors.</b></p>
      <p>In case of use of any trademark, patent, image, text, copyright or other intellectual property or other right, you may be required by GranPlay to prove that the rights are yours or that you are authorized to use them. If you do not prove the authorization or right in the period requested by GranPlay or the proof is not enough, at GranPlay's discretion, the content may be withdrawn by us. However, GranPlay is not required to request the evidence and may withdraw content or even registration and participation that it deems conflicting at any time, either to third parties, to itself or to the Law and these Terms. GranPlay does not undertake to give any right of reply or appeal.</p>
      <p><b class="bold-text">If you check for any act that you believe to be a breach of a third party's right to use or connect to our applications, you must notify us about it.</b> If the right is yours, please send us the certificate or proof of the right, including:</p>
      <p>(A) identification of the work that is alleged to have been violated; (B) identification of alleged infringing material and sufficient information to enable us to locate the material in the applications (from the URL (s) of alleged infringement and indication of exact page location, date and time; (D) a statement in good faith that the contested use is not authorized by the rights owner, its agent or by law; (E) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright or intellectual property on behalf of the owner and (F) your physical or electronic signature. should be sent to: contato@granplay.com</p>
      <p>GranPlay is not a Trial, Intermediation, Mediation, Arbitration or other body and will make its decisions based on its own criteria that it deems convenient, without the need for any explanation, argumentation, term, guarantee of response or otherwise.</p>
      <h2>13. Contractual Relationship</h2>
      <p><b class="bold-text">Your relationship with GranPlay is licensed to use the applications, partner, and there is no relationship or employment link, collaboration or work with you ,</b> unless it is expressly contracted by us.</p>
      <p>Even if you make publications about us or publish issues relating to you, there is no obligation to pay you in any way.</p>
      <p>Both you and GranPlay may terminate the agreement with each other at any time, without notice, however, and the obligations already assumed to users must be duly fulfilled, even after termination of the agreement. For example, activities already marked and confirmed should be performed.</p>
      <p>These Terms may be terminated at any time by the defaulting party and without prior notice and immediately in the event of (i) breach by the other party of any of the terms and conditions set forth herein; (ii) violation of the General Rules of the applications, system or platform (iii) insolvency, bankruptcy or judicial or extrajudicial recovery of the other party.</p>
      <p>Should any of the Parties wish to terminate these Terms unreasonably, it may forward a notice to the other Party, 90 (ninety) days in advance, informing them of their desire to terminate the relationship established herein.</p>
      <p>The cancellation by the Association must be done through the website or by sending an email to: contato@granplay.com, under the title CANCELLATION, and you must wait for the email confirmation of the cancellation by GranPlay, as provided in the application.</p>
      <h2>14. Disputes Between Associations, Users, Members Or Third Parties:</h2>
      <p><b class="bold-text">You are fully responsible for your interactions with third parties with whom you interact, even though through our applications. GranPlay reserves the right, but has no obligation, to engage in any of these disputes or issues.</b></p>
      <h2>15. Other Provisions Regarding Waiver Of Liability:</h2>
      <p><b class="bold-text">GranPlay is not responsible for and makes no warranty, implied or explicit, as to the contents of users, Associations and third parties or the accuracy and reliability of content of users or third parties posted through or in connection with the Applications and the contents of users or third parties do not necessarily reflect our opinion.</b></p>
      <p>GranPlay shall not be liable for any damage, loss or loss caused by third parties or by Users of the services or applications or by any of the equipment or programming and software associated with or used in the Services and Applications.</p>
      <p>GranPlay is not responsible for the conduct, whether online or offline, of any user, Association or third party.</p>
      <p>Likewise, we are not responsible and you will not be able to sue or complain to us for any defect, error, omission, delay, interruption, improper collection, omission and others in the operation or transmission of communication or data, provider, server, or other. We are not responsible for any problem or malfunction of devices, telephone networks, internet, equipment, software, problems sending or receiving emails and can not be held responsible for any losses, damages and damages caused to you or your equipment , death and others arising out of the use or connection with our applications and services or third parties that we indicate or the relations that you will have as a result of our applications.</p>
      <p><b class="bold-text">The services are provided "as is" and as available and GranPlay expressly accepts no responsibility and makes no warranty of fitness for a particular purpose or non-infringement.</b> GranPlay can not guarantee or promise any specific results from and for the use of the applications or services, even to Partner Associations.</p>
      <p>GranPlay receives and relies on information and services from third parties and is not responsible for its accuracy and validity. This includes, but is not limited to, your location, weather (weather), calendar, language, location of places, names of places and people, prices, quality, opening and closing time, restrictions, images and others. <b class="bold-text">You agree to check in and with the places and users that you are interested, and directly with them, if the information we pass on you is up to date and accurate. If you are not precise, you should tell us about it.</b></p>
      <p>GranPlay, its applications and services used by GranPlay may maintain for a period of 6 months or more of your connection data, access data, user and any other legal data.</p>
      <p><b class="bold-text">IN NO EVENT WILL GRANPLAY BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES, EXEMPLARY, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS ARISING OUT OF THE USE OF THE SERVICES AND APPLICATIONS, EVEN IF THE GRANPLAY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. REGARDLESS OF ANY REPRESENTATION OTHERWISE CONTAINED IN THIS AGREEMENT OR IN OUR POLICIES, THE LIABILITY OF THE GRANPLAY FOR ANY CAUSE AND REGARDLESS OF THE FORM OF THE ACTION WILL ALWAYS BE LIMITED TO THE AMOUNT PAID OR TO BE RECEIVED, IF ANY, BY YOU FOR GRANPLAY RELATED TO SERVICES.</b></p>
      <p>Softwares made available in connection with the applications or services may be subject to export and sale controls. No software or application should be downloaded from the applications or otherwise exported or "exported" if there is any legal violation. To download or use the software are at your own risk.</p>
      <p><b class="bold-text">You agree to indemnify and hold GranPlay, its subsidiaries and affiliates, subcontractors, and other partners, and their respective officers, directors, agents, officers, partners, employees and volunteers harmless from any loss, liability, claim or demand, including, but not limited to, limited to reasonable attorneys' fees, made by any third party due to or arising out of your use of the Services or Applications in violation of these Terms and Conditions arising from a breach of this Agreement or any breach of your representations and warranties set forth in this Agreement or any content you post on, through or in connection with the Services or Applications. GranPlay will not provide any editorial control of the content posted by users,</b></p>
      <h2>16. Final Provisions:</h2>
      <p><b class="bold-text">The failure or delay of GranPlay to exercise or enforce any right or provision in these Terms, in whole or in part, shall not be construed as a waiver of such rights or provisions or even and especially the remainder of the Terms.</b></p>
      <p>The division in titles or numbers of the present Term is done by mere convenience, having no legal or contractual effect. This Term operates to the maximum extent permitted by law.</p>
      <p>If any provision of this Agreement or other document in our applications is unlawful, void or unenforceable, that provision shall be deemed severable from this Agreement and shall not affect the validity and enforceability of any remaining provisions.</p>
      <p><b class="bold-text">The Association or user may not assign or transfer to any third party, in whole or in part, their rights and obligations under these Terms of Use.</b></p>
      <p><b class="bold-text">To contact us regarding any questions about this agreement, please fill out the form on the "Contact Us" page.</b></p>
      <p>Although it may have international validity, the Central Court of the City of São Paulo, São Paulo State, is elected as the sole authority to settle any controversies arising from this instrument, regardless of any other, however privileged it may be or may to be.</p>


    </div>
  </div>

</div>

<style>
.pink {
  color:#DB7093	;
}

.bold-text {
  color:black;
}
</style>
